//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChateauEntity.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Chateau_V2Entities : DbContext
    {
        public Chateau_V2Entities()
            : base("name=Chateau_V2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAdminUsers> tAdminUsers { get; set; }
        public virtual DbSet<tChateauKnives> tChateauKnives { get; set; }
        public virtual DbSet<tOrderDetails> tOrderDetails { get; set; }
        public virtual DbSet<tOrders> tOrders { get; set; }
        public virtual DbSet<tSiteFlowOrderPushManual> tSiteFlowOrderPushManual { get; set; }
        public virtual DbSet<tSiteFlowResponse> tSiteFlowResponse { get; set; }
    }
}
