//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChateauEntity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChateauBelfield
    {
        public long Id { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string OrderReference { get; set; }
        public string OrderDetailsReference { get; set; }
        public string BarCode { get; set; }
        public string AttributeDesignCode { get; set; }
        public string AttributeLength { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ArtworkUrl { get; set; }
        public Nullable<bool> EmailSentToProduction { get; set; }
        public Nullable<System.DateTime> EmailSentDatetime { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
