//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChateauEntity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChateauPreOrder
    {
        public long Id { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string OrderReference { get; set; }
        public string OrderDetailsReference { get; set; }
        public string BarCode { get; set; }
        public string Substrate { get; set; }
        public string Attribute { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ArtworkUrl { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress1 { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerAddress3 { get; set; }
        public string CustomerTown { get; set; }
        public string CustomerState { get; set; }
        public string CustomerPostcode { get; set; }
        public string CustomerCountry { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerCompanyName { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<bool> EmailSentToProduction { get; set; }
        public Nullable<System.DateTime> EmailSentDatetime { get; set; }
    }
}
