//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChateauEntity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tOrders()
        {
            this.tOrderDetails = new HashSet<tOrderDetails>();
        }
    
        public long ID { get; set; }
        public string ReferenceNumber { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> SentToSiteFlow { get; set; }
        public Nullable<System.DateTime> SiteflowSentDatetme { get; set; }
        public string OriginalSiteflowJson { get; set; }
        public string ModifiedSiteflowJson { get; set; }
        public string SiteflowOrderStatus { get; set; }
        public string DeleteNotes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrderDetails> tOrderDetails { get; set; }
    }
}
