//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChateauEntity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrderDetails
    {
        public long ID { get; set; }
        public string ReferenceNumber { get; set; }
        public long OrderId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string SKU { get; set; }
        public string Substrate { get; set; }
        public string Status { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Artwork { get; set; }
    
        public virtual tOrders tOrders { get; set; }
    }
}
