//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChateauEntity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSiteFlowResponse
    {
        public long ID { get; set; }
        public long OrderId { get; set; }
        public string Response { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
