//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicsMeEntity.MediaClipEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCustomer()
        {
            this.tMediaClipOrder = new HashSet<tMediaClipOrder>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMediaClipOrder> tMediaClipOrder { get; set; }
    }
}
