//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChateauEntity.MediaClipEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMediaClipOrderExtrinsic
    {
        public long ExtrinsicId { get; set; }
        public long MediaClipOrderDetailsId { get; set; }
        public string ExtrinsicName { get; set; }
        public string ExtrinsicValue { get; set; }
    
        public virtual tMediaClipOrderDetails tMediaClipOrderDetails { get; set; }
    }
}
